apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: evolve-todo-prod

namePrefix: prod-

bases:
  - ../../base

patchesStrategicMerge:
  - backend-deployment-patch.yaml
  - frontend-deployment-patch.yaml

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - environment=production
      - log-level=info
  - name: frontend-config
    behavior: merge
    literals:
      - node-env=production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3
