apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evolve-todo.fullname" . }}-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "evolve-todo.backend.labels" . | nindent 4 }}
data:
  environment: {{ .Values.backend.env.environment | quote }}
  log-level: {{ .Values.backend.env.logLevel | quote }}
  cors-origins: {{ .Values.backend.env.corsOrigins | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evolve-todo.fullname" . }}-frontend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "evolve-todo.frontend.labels" . | nindent 4 }}
data:
  api-url: {{ .Values.frontend.env.apiUrl | quote }}
  node-env: {{ .Values.frontend.env.nodeEnv | quote }}
