apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: evolve-todo

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-configmap.yaml
  - ingress.yaml

commonLabels:
  app: evolve-todo
  managed-by: kustomize
